version: '3'
services:
  redismaster1:
    image: redis:4.0.9
    ports:
      - "7000:7000"
      - "17000:17000"
    volumes:
      - ./docker-data/redis-cluster1.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      mqtt:
#        ipv4_address: 10.168.81.101
    restart: unless-stopped
  redismaster2:
    image: redis:4.0.9
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
      - ./docker-data/redis-cluster2.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      mqtt:
#        ipv4_address: 10.168.81.102
    restart: unless-stopped
  redismaster3:
    image: redis:4.0.9
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - ./docker-data/redis-cluster3.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      mqtt:
#        ipv4_address: 10.168.81.103
    restart: unless-stopped
  redislave1:
    image: redis:4.0.9
    ports:
      - "7003:7003"
      - "17003:17003"
    volumes:
      - ./docker-data/redis-cluster4.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      mqtt:
#        ipv4_address: 10.168.81.104
    restart: unless-stopped
  redislave2:
    image: redis:4.0.9
    ports:
      - "7004:7004"
      - "17004:17004"
    volumes:
      - ./docker-data/redis-cluster5.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      mqtt:
#        ipv4_address: 10.168.81.105
    restart: unless-stopped
  redislave3:
    image: redis:4.0.9
    ports:
      - "7005:7005"
      - "17005:17005"
    volumes:
      - ./docker-data/redis-cluster6.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      mqtt:
#        ipv4_address: 10.168.81.106
    restart: unless-stopped
  redis-cluster:
    tty: true
    build:
      context: .
      args:
        redis_version: '4.0.9'
    hostname: server
    depends_on:
      - redismaster1
      - redismaster2
      - redismaster3
      - redislave1
      - redislave2
      - redislave3
    networks:
      mqtt:
#        ipv4_address: 10.168.81.100
networks:
  mqtt:
    external:
      name: mqtt
